import { NextRequest, NextResponse } from "next/server"
import { dbConnect } from "@/app/lib/mongoose"
import User from "@/app/model/User"
import bcrypt from "bcryptjs"
import { signJwt } from "@/app/lib/auth"
